# Change 'comments' to true for Disqus comments
#disqus:
#  comments: false
#  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-32412Y6YPE'

menu:
- {name: '일상',         url: 'daily'}
- {name: '발견',         url: 'discovery'}
- {name: '기술',         url: 'tech'}
- {name: '참고문서',      url: 'reference'}
- {name: 'Information',         url: 'info'}
- {name: 'About',       url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link:   'https://www.facebook.com/parkkw09'}
- {icon: 'instagram', link:  'https://instagram.com/double_dragon_84'}
- {icon: 'github', link:    'https://github.com/parkkw09'}
- {icon: 'linkedin', link:    'https://www.linkedin.com/in/parkkw09/'}
- {icon: 'envelope', link:   'mailto:parkkw09@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '다음장'
  previous_page: '이전장'

sharing_button_prompt: '공유하세요!'

related_posts: '관련 포스트'

post_date_prefix: 'Written on'
